-- MySQL Script generated by MySQL Workbench
-- Tue Jan 31 09:32:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';

-- -----------------------------------------------------
-- Schema bulletin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bulletin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bulletin` DEFAULT CHARACTER SET utf8 ;
USE `bulletin` ;

-- -----------------------------------------------------
-- Table `bulletin`.`bulletin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bulletin`.`bulletin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NULL,
  `description` LONGTEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
