-- MySQL Script generated by MySQL Workbench
-- Tue Jan 31 00:09:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE="";

-- -----------------------------------------------------
-- Schema raffle_entry
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema raffle_entry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `raffle_entry` DEFAULT CHARACTER SET utf8 ;
USE `raffle_entry` ;

-- -----------------------------------------------------
-- Table `raffle_entry`.`raffle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `raffle_entry`.`raffle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contact_number` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `contact_number_UNIQUE` (`contact_number` ASC) VISIBLE)
ENGINE = InnoDB;

CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
